spring.datasource.url=${DATABASE_URL}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

spring.security.user.name=mrodriguez
spring.security.user.password=123456